server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: auth-service

  datasource  :
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization:
      true
    sql:
      init:
        mode:
          always
        data-locations:
          classpath:data.sql


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900
  refresh-token-expiration: 604800

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL}/eureka