services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network
  
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - ecom-network

  discovery-service:
    build: ./discovery-service
    environment: 
      SERVER_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - ecom-network

  auth-service:
    build: ./auth-service
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    # ports:
    #   - "8000:8000"

    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_SERVICE_URL: discovery-service:8761
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ecom-network

  product-service:
    build: ./product-service
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      SERVER_PORT: 8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
    # ports:
    #   - "8001:8001"

    networks:
      - ecom-network

  order-service:
    build: ./order-service
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      SERVER_PORT: 8002
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
    # ports:
    #   - "8002:8002"

    networks:
      - ecom-network

  inventory-service:
    build: ./inventory-service
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      SERVER_PORT: 8003
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
    # ports:
    #   - "8003:8003"
    networks:
      - ecom-network

  api-gateway:
    build: ./api-gateway
    depends_on:
      discovery-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVICE_URL: discovery-service:8761
    ports:
      - "8080:8080"
    networks:
      - ecom-network

volumes:
  pgdata:

networks:
  ecom-network:
    driver: bridge