services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nithin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - ecom-network
  
  auth-service:
    build: ./auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: nithin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - ecom-network

  product-service:
    build: ./product-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: nithin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

    networks:
      - ecom-network

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
