server:
  port: 8002

spring:
  application:
    name: order-service
  web:
    resources:
      add-mappings: false
  datasource  :
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

client:
  product:
    base-url: http://localhost:8001

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka