server:
  port: 8001

spring:
  application:
    name: product-service

  datasource  :
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization:
      true
    sql:
      init:
        mode:
          always
        data-locations:
          classpath:data.sql

  kafka:
    bootstrap-servers: localhost:9092

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka