server:
  port: 8003

spring:
  application:
    name: inventory-service

  datasource  :
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization:
      true
    sql:
      init:
        mode:
          always
        data-locations:
          classpath:data.sql


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    root: DEBUG
