server:
  port: ${SERVER_PORT:8003}

spring:
  application:
    name: inventory-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization:
      true
    sql:
      init:
        mode:
          always
        data-locations:
          classpath:data.sql


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: inventory-group

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL}/eureka
#logging:
#  level:
#    root: DEBUG
